### ISSUE TITLE
Does not work ! (Please respond)

### ISSUE THREAD

**Issue by KorigamiK** [EL-S/KickassAnimeDownloader#2]
Would you like to work together in making it work again?
please kicksassanime has some of the lowest size downloads in the animo-pace-stream.io source.

Sincerely wating for your reply !
Regards

**Comment by EL-S** [comment]
Sorry I didn't see your issue until now :)

I noticed you've started your own anime downloader, and before I saw this I was planning on submitting a pull request to clean some things up in yours haha

I don't really remember making this script anymore, but I can have a go at fixing the problems, from a quick glance the download function call is actually commented it which may be the problem.

I'll take a look soon but feel free to submit any pull requests if you like and I'd be happy to test and merge them :)

**Comment by KorigamiK** [comment]
Yes! I will definitely try to make it working again, but I have noticed that using selenium is definitely not the best choice, it's slow and to get it working for common folk is a hassle.( You can check by running my original batch anime downloader )

 I would like to make it work without the need for a browser. But I'm stuck on how to parse webpages with javascript, is there even a way? If you have any advice on this please enlighten me. P.S. it was the fact that your script stopped that I decided to make my own, thanks :)

**Comment by EL-S** [comment]
So far I haven't really found any good way to parse JavaScript in Python sorry :(

Usually when there is JavaScript, I use some manual string methods like split and replace as the information I need is usually a URL or something that doesn't change often, like a code to decrypt something.

Selenium can be quite slow, but if you use it with chrome driver headlessly, you should get some improvement (and it won't pop up on your screen unnecessarily).

Good to hear some of my scripts have been useful for others :)

**Comment by KorigamiK** [comment]
Yeah, that's what I did for yugenani. Its good enough for now but that's too much work for a website which basically runs on javascript (I'm talking about kickassanime) so I want to ask if animo-pace-stream.io is a server specific to kick-ass anime or is there any other website that uses it? If you're able to find any please let me know.

Regards

**Comment by KorigamiK** [comment]
Hey, I have made a [scraper](https://github.com/KorigamiK/animepace-scraper) for animepace which has the same servers as kickassanime but is faster, I feel that it is almost complete.

Thank you
Regards.
